# Various checks to verify the cargo workspace and its crates are correctly configured.
name: "Workspace features"

on:
  push:
    branches: ["main", "release-*"]
  pull_request:
  workflow_dispatch:

# cancel previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check workspace features
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set rust version via common env file
        run: cat .github/env >> $GITHUB_ENV

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "${{env.RUST_STABLE_VERSION}}"

      - name: Install Zepter
        run: cargo install --locked -q zepter && zepter --version

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Check features
        working-directory: ${{ github.workspace }}
        run: |
          zepter run check
          zepter transpose dep lift-to-workspace 'regex:.*'
